spring.application.name=backend_medic

# Configuration de la connexion à la Base de Données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Votrebasedonnee?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=nomutilisateur
# Remplace 'ton_mot_de_passe' par le vrai mot de passe de ton utilisateur root MySQL
spring.datasource.password=motdepasse
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuration de la cle secrete de l'adminitrateur
app.jwt.secret=Ju57hYWwrE+ebqonKrfXLgCKFKNZhHeZ6QAylqmu2OY=
app.jwt.expiration-ms=86400000
app.admin.secret-key=cle secrete pour l'admin